### ISSUE TITLE
Maintaining user groups for Rings on the FEM Forum

### ISSUE THREAD

**Issue by jpitts** [ethereum-magicians/scrolls#51] opened 2019-01-08 19:08 UTC
This is for a @ligi suggestion for messaging members of a particular ring inside of FEM Forum messages.

https://ethereum-magicians.org/t/ping-a-ring-from-a-post/2356

**Comment by bmann** [comment] 2019-01-08 19:14
This is a duplicate of #14 and related to #37

**Closed as completed** 2019-03-12 23:35 UTC
Labels: forum
